### PR TITLE
fixing breakage from SqlAlchemy 1.4

### PR DESCRIPTION
**Pull request by aaronsmith1234**
Seems like it fixes it, all tests passed. Also a bit scared about the code embedded in the Chinese I had to change, but tests pass....

### CODE REVIEW

**Review by evladik — APPROVED** [review]

**Comment by aaronsmith1234** [comment]
@evladik doesn't look like this ever got merged; anything else you need me to do?

**Comment by jsbain** [comment]
Someone probably ought to remove the except/pass that hides the reason for the failure!

**Comment by aaronsmith1234** [comment]
@jsbain yeah, I thought about that, but wasn't sure why it had been put in, so took the minimal route of at least getting the code working again with SA 1.4, and not trying to overhaul too much. @evladik @MacHu-GWU any reason not to merge?

**Comment by MacHu-GWU** [comment]
@aaronsmith1234  Awesome, sorry I didn't realize it is fixed yet. The reason why I am not very active on updating this version is because I am crawling the up-to-date dataset based on 2020 Census and IRS data. Plan to issue a 2.x versioin in two month. Thank you for your contribution!

**Comment by aaronsmith1234** [comment]
@MacHu-GWU can you push a new version to pypi? If not, everyone who downloads the current version and the newest sql alchemy will run into issues (like our current ci build is).

**Comment by MacHu-GWU** [comment]
@aaronsmith1234  Yes, will do today.

**Comment by aaronsmith1234** [comment]
Hey @MacHu-GWU , just checking in, can you push a version with the fix above to pypi? Causing our CI builds to fail. Thanks!! Awesome package, appreciate all the good work!

**Comment by MacHu-GWU** [comment]
@aaronsmith1234  Sorry for that will release one from master now. BTW, you could fork one from this repo and use pip to install from your own github repo. This is how I usually solve it when my project depends on an open-source project that missing some feature.

**Comment by MacHu-GWU** [comment]
@aaronsmith1234  please check ``pip install uszipcode==0.2.5``

**Pull request merged**
